# Actividad: Arrays Unidimensionales
## 1.- Crea un vector con valores dentro del rango 3 a el número que representa tu edad.

In [1]:
import numpy as np

In [2]:
edad=30
vector=np.array(list(range(3,31)))
vector

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

## 2.- Crea un arreglo con los siguientes elementos: [0, 1, 2, 3, 4, 0, 1, 2, 3, 4]

In [3]:
lista=[0,1,2,3,4]
arreglo=np.array(lista+lista)
arreglo

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

## 3.- Ordena de forma ascendiente dicho arreglo.  

In [4]:
arreglo.sort()
arreglo

array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4])